name: app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.4+1
  flutter_dotenv: ^3.1.0
  get_it: ^5.0.6
  get: ^3.24.0
  dio: ^3.0.10
  path_provider: ^1.6.27
  provider: ^4.3.3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.11.1
  json_serializable: ^3.5.1
  analyzer:

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/data.json
    - assets/splash_icon.jpg
    - assets/bmw_logo.png
    - assets/toyota_logo.png
    - assets/rolls_royce_logo.png
    - assets/general_motors_logo.png
    - assets/mini_logo.png
    - assets/first_route_image.png